before_script:
  - python --version
  - pip install pytest-cov

unittest:
  script:
    - cd code
    - python -m unittest discover

after_script:
  - PYTHONPATH="selfish_proxy" py.test --cov=selfish_proxy tests
