before_script:
  - python --version
  - pip install coverage

unittest:
  script:
    - cd code
    - PYTHONPATH="selfish_proxy" coverage run --include=selfish* -m unittest discover
    - coverage report -m
