#Titel [max. 75 Zeichen]:
Simulation verschiedener Selfish-Mining-Strategien in Bitcoin

#Kurzbeschreibung [mind. 200 - max. 535 Zeichen]:
Im Zuge der Diplomarbeit werden unterschiedliche Strategien des Selfish-Mining-Angriffs simuliert und dem gewöhnlichen Mining gegenübergestellt.
Dafür wird eine Docker-basierte Simulationssoftware implementiert, die durch die Verwendung der Bitcoin-Referenzimplementierung und die Berücksichtigung des Peer-to-Peer-Netzwerk, eine realistische und bis jetzt noch nicht durchgeführte Simulierung ermöglicht.
Die Ergebnisse der Simulierung verdeutlichen die Relevanz von Selfish-Mining als Angriff auf das Bitcoin-System. 

#Aufzählung – Ihre Abschlussarbeit/Projekt im Überblick [3 frei wählbare Überschriften & Unterpunkte – max. 500 Zeichen]:

##Diplomarbeit im Bereich Blockchain
* Docker-basierte Simulation des Selfish-Mining-Angriffes in Bitcoin
* Vergleichende Analyse zu normalen Mining
* Resultate untermauern die Relevanz von Selfish-Mining

## Wissenschaftlicher Fortschritt
* Direkte Wiederverwendung der Bitcoin-Referenzimplementierung
* Simulierung der Latenz des Netzwerkes

## Über die Diplomarbeit hinaus
* Professionelles open-sourcen der Simulationssoftware
* Vorstellung der Software der österreichischen Blockchain-Community

